name: Test SSH Connection to EC2

on:
  workflow_dispatch:   # allows manual run from GitHub Actions tab

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "✅ Connected successfully to EC2 instance!"
            hostname
            whoami
            uptime
